/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_replay_free: (a: number, b: number) => void;
export const __wbg_trace_free: (a: number, b: number) => void;
export const replayAvailable: () => number;
export const replay_exportState: (a: number) => [number, number, number, number];
export const replay_finish: (a: number) => [number, number, number];
export const replay_isComplete: (a: number) => number;
export const replay_prepare: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
export const replay_prepareCall: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => [number, number, number];
export const replay_provideState: (a: number, b: number, c: number) => [number, number];
export const replay_run: (a: number) => [number, number, number, number];
export const replay_status: (a: number) => [number, number, number, number];
export const trace_attachEthdebug: (a: number, b: number, c: number) => [number, number];
export const trace_fromJson: (a: number, b: number) => [number, number, number];
export const trace_fromSimulation: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number];
export const trace_fromTransaction: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const trace_hasEthdebug: (a: number) => number;
export const trace_provideCode: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const trace_state: (a: number, b: number) => [number, number, number, number];
export const trace_step: (a: number, b: number) => [number, number, number, number];
export const trace_stepCount: (a: number) => number;
export const trace_summary: (a: number) => [number, number, number, number];
export const trace_toJson: (a: number) => [number, number, number, number];
export const version: () => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
